// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductInterface": {
      "properties": {
        "id": {
          "title": "ProductInterface.id",
          "type": "string"
        },
        "title": {
          "title": "ProductInterface.title",
          "type": "string"
        },
        "description": {
          "title": "ProductInterface.description",
          "type": "string"
        },
        "price": {
          "title": "ProductInterface.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price"
      ],
      "additionalProperties": false,
      "title": "ProductInterface",
      "type": "object"
    },
    "StockInterface": {
      "properties": {
        "productId": {
          "$ref": "#/definitions/AttributeValue",
          "title": "StockInterface.productId"
        },
        "count": {
          "$ref": "#/definitions/AttributeValue",
          "title": "StockInterface.count"
        }
      },
      "required": [
        "productId",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockInterface",
      "type": "object"
    },
    "ProductServiceInterface": {
      "properties": {
        "getProductById": {
          "title": "ProductServiceInterface.getProductById"
        },
        "getAllProducts": {
          "title": "ProductServiceInterface.getAllProducts"
        },
        "createProduct": {
          "title": "ProductServiceInterface.createProduct"
        }
      },
      "required": [
        "getProductById",
        "getAllProducts",
        "createProduct"
      ],
      "additionalProperties": false,
      "title": "ProductServiceInterface",
      "type": "object"
    },
    "StockServiceInterface": {
      "properties": {
        "getCreateStockTranskItem": {
          "title": "StockServiceInterface.getCreateStockTranskItem"
        },
        "getStockByProductId": {
          "title": "StockServiceInterface.getStockByProductId"
        },
        "getStock": {
          "title": "StockServiceInterface.getStock"
        }
      },
      "required": [
        "getCreateStockTranskItem",
        "getStockByProductId",
        "getStock"
      ],
      "additionalProperties": false,
      "title": "StockServiceInterface",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};